name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        
            

        - name: Set up Node.js
            uses: actions/complaint-management-system
            with:
                node-version: '14'

        - name: Install dependencies
            run: npm install

        - name: Run tests
            run: npm test
