
    uses: appleboy/ssh-action@v1.0.3[3]
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_PRIVATE_KEY }}
      script: |
        set -e
        cd /var/www/complaints-app/complaint-management-system
        if [ -d ".git" ]; then
          git pull
        else
          git clone --depth 1 git@github.com:Druvithaa/complaint-management-system.git .
        fi
        cd backend
        npm ci
        pm2 start server.js --name complaints-api || pm2 restart complaints-api
        pm2 save[3]
